package com.cavan.greendao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table GROUP_INFO.
 */
public class GroupInfo {

    private Long id;
    private String name;
    private String description;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public GroupInfo() {
    }

    public GroupInfo(Long id) {
        this.id = id;
    }

    public GroupInfo(Long id, String name, String description) {
        this.id = id;
        this.name = name;
        this.description = description;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    // KEEP METHODS - put your custom methods here

    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        builder.append("[id:");
        builder.append(id);
        builder.append(", name:");
        builder.append(name);
        builder.append(", description:");
        builder.append(description);
        builder.append(']');
        return builder.toString();
    }
    // KEEP METHODS END

}
