package com.cavan.greendao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table USER_INFO.
 */
public class UserInfo {

    private Long id;
    private String name;
    private Boolean sex;
    private Integer age;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public UserInfo() {
    }

    public UserInfo(Long id) {
        this.id = id;
    }

    public UserInfo(Long id, String name, Boolean sex, Integer age) {
        this.id = id;
        this.name = name;
        this.sex = sex;
        this.age = age;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Boolean getSex() {
        return sex;
    }

    public void setSex(Boolean sex) {
        this.sex = sex;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    // KEEP METHODS - put your custom methods here

    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        builder.append("[id:");
        builder.append(id);
        builder.append(", name:");
        builder.append(name);
        builder.append(", sex:");
        builder.append(sex);
        builder.append(", age:");
        builder.append(age);
        builder.append(']');
        return builder.toString();
    }
    // KEEP METHODS END

}
