/* This file was automatically generated by Fuang.Cao, Do not modify */

#include "CavanMain.h"

extern int do_cavan_abspath(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doAbspath(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "abspath", do_cavan_abspath);
}

extern int do_cavan_alarm(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doAlarm(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "alarm", do_cavan_alarm);
}

extern int do_cavan_alc5671_clock(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doAlc5671Clock(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "alc5671_clock", do_cavan_alc5671_clock);
}

extern int do_cavan_auto_dd(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doAutoDd(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "auto_dd", do_cavan_auto_dd);
}

extern int do_cavan_auto_input(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doAutoInput(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "auto_input", do_cavan_auto_input);
}

extern int do_cavan_auto_mount(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doAutoMount(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "auto_mount", do_cavan_auto_mount);
}

extern int do_cavan_battery(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doBattery(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "battery", do_cavan_battery);
}

extern int do_cavan_battery_level(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doBatteryLevel(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "battery_level", do_cavan_battery_level);
}

extern int do_cavan_bdata(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doBdata(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "bdata", do_cavan_bdata);
}

extern int do_cavan_bkernel(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doBkernel(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "bkernel", do_cavan_bkernel);
}

extern int do_cavan_bmp_view(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doBmpView(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "bmp_view", do_cavan_bmp_view);
}

extern int do_cavan_bootimg(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doBootimg(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "bootimg", do_cavan_bootimg);
}

extern int do_cavan_bramdisk(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doBramdisk(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "bramdisk", do_cavan_bramdisk);
}

extern int do_cavan_brecovery(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doBrecovery(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "brecovery", do_cavan_brecovery);
}

extern int do_cavan_bsystem(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doBsystem(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "bsystem", do_cavan_bsystem);
}

extern int do_cavan_buboot(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doBuboot(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "buboot", do_cavan_buboot);
}

extern int do_cavan_calculator(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doCalculator(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "calculator", do_cavan_calculator);
}

extern int do_cavan_chroot(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doChroot(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "chroot", do_cavan_chroot);
}

extern int do_cavan_chtty(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doChtty(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "chtty", do_cavan_chtty);
}

extern int do_cavan_copy(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doCopy(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "copy", do_cavan_copy);
}

extern int do_cavan_dd(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doDd(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "dd", do_cavan_dd);
}

extern int do_cavan_df(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doDf(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "df", do_cavan_df);
}

extern int do_cavan_display(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doDisplay(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "display", do_cavan_display);
}

extern int do_cavan_dos2unix(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doDos2unix(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "dos2unix", do_cavan_dos2unix);
}

extern int do_cavan_eavoo_sell_statistic(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doEavooSellStatistic(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "eavoo_sell_statistic", do_cavan_eavoo_sell_statistic);
}

extern int do_cavan_ecc(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doEcc(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "ecc", do_cavan_ecc);
}

extern int do_cavan_event_repeater(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doEventRepeater(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "event_repeater", do_cavan_event_repeater);
}

extern int do_cavan_ext2(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doExt2(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "ext2", do_cavan_ext2);
}

extern int do_cavan_fb_capture(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doFbCapture(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "fb_capture", do_cavan_fb_capture);
}

extern int do_cavan_fdisk(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doFdisk(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "fdisk", do_cavan_fdisk);
}

extern int do_cavan_file_crc32(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doFileCrc32(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "file_crc32", do_cavan_file_crc32);
}

extern int do_cavan_file_join(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doFileJoin(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "file_join", do_cavan_file_join);
}

extern int do_cavan_file_loop(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doFileLoop(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "file_loop", do_cavan_file_loop);
}

extern int do_cavan_file_split(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doFileSplit(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "file_split", do_cavan_file_split);
}

extern int do_cavan_ftp(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doFtp(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "ftp", do_cavan_ftp);
}

extern int do_cavan_ftp_server(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doFtpServer(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "ftp_server", do_cavan_ftp_server);
}

extern int do_cavan_git_daemon(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doGitDaemon(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "git_daemon", do_cavan_git_daemon);
}

extern int do_cavan_heart_rate(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doHeartRate(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "heart_rate", do_cavan_heart_rate);
}

extern int do_cavan_i2c(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doI2c(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "i2c", do_cavan_i2c);
}

extern int do_cavan_image_dd(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doImageDd(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "image_dd", do_cavan_image_dd);
}

extern int do_cavan_inotify(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doInotify(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "inotify", do_cavan_inotify);
}

extern int do_cavan_input(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doInput(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "input", do_cavan_input);
}

extern int do_cavan_jw650_lcd(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doJw650Lcd(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "jw650_lcd", do_cavan_jw650_lcd);
}

extern int do_cavan_jwp_udp(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doJwpUdp(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "jwp_udp", do_cavan_jwp_udp);
}

extern int do_cavan_lm49350_clock(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doLm49350Clock(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "lm49350_clock", do_cavan_lm49350_clock);
}

extern int do_cavan_loop_run(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doLoopRun(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "loop_run", do_cavan_loop_run);
}

extern int do_cavan_md5sum(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doMd5sum(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "md5sum", do_cavan_md5sum);
}

extern int do_cavan_mkdir(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doMkdir(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "mkdir", do_cavan_mkdir);
}

extern int do_cavan_mknp(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doMknp(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "mknp", do_cavan_mknp);
}

extern int do_cavan_mksdcard(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doMksdcard(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "mksdcard", do_cavan_mksdcard);
}

extern int do_cavan_modem_upgrade(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doModemUpgrade(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "modem_upgrade", do_cavan_modem_upgrade);
}

extern int do_cavan_mount(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doMount(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "mount", do_cavan_mount);
}

extern int do_cavan_move(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doMove(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "move", do_cavan_move);
}

extern int do_cavan_mtd(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doMtd(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "mtd", do_cavan_mtd);
}

extern int do_cavan_net_discovery(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doNetDiscovery(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "net_discovery", do_cavan_net_discovery);
}

extern int do_cavan_net_monitor(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doNetMonitor(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "net_monitor", do_cavan_net_monitor);
}

extern int do_cavan_part_probe(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doPartProbe(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "part_probe", do_cavan_part_probe);
}

extern int do_cavan_part_show(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doPartShow(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "part_show", do_cavan_part_show);
}

extern int do_cavan_part_table(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doPartTable(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "part_table", do_cavan_part_table);
}

extern int do_cavan_ping(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doPing(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "ping", do_cavan_ping);
}

extern int do_cavan_poll_event(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doPollEvent(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "poll_event", do_cavan_poll_event);
}

extern int do_cavan_poll_input(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doPollInput(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "poll_input", do_cavan_poll_input);
}

extern int do_cavan_ramdisk(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doRamdisk(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "ramdisk", do_cavan_ramdisk);
}

extern int do_cavan_remove(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doRemove(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "remove", do_cavan_remove);
}

extern int do_cavan_resize(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doResize(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "resize", do_cavan_resize);
}

extern int do_cavan_rle(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doRle(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "rle", do_cavan_rle);
}

extern int do_cavan_screen_mirror(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doScreenMirror(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "screen_mirror", do_cavan_screen_mirror);
}

extern int do_cavan_service(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doService(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "service", do_cavan_service);
}

extern int do_cavan_sha1sum(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doSha1sum(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "sha1sum", do_cavan_sha1sum);
}

extern int do_cavan_show_file(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doShowFile(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "show_file", do_cavan_show_file);
}

extern int do_cavan_shrink(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doShrink(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "shrink", do_cavan_shrink);
}

extern int do_cavan_sprd_at(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doSprdAt(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "sprd_at", do_cavan_sprd_at);
}

extern int do_cavan_sprd_write_imei(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doSprdWriteImei(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "sprd_write_imei", do_cavan_sprd_write_imei);
}

extern int do_cavan_ssh(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doSsh(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "ssh", do_cavan_ssh);
}

extern int do_cavan_ssh_copy(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doSshCopy(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "ssh_copy", do_cavan_ssh_copy);
}

extern int do_cavan_sshd(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doSshd(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "sshd", do_cavan_sshd);
}

extern int do_cavan_ssh_dd(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doSshDd(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "ssh_dd", do_cavan_ssh_dd);
}

extern int do_cavan_su(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doSu(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "su", do_cavan_su);
}

extern int do_cavan_sudo(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doSudo(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "sudo", do_cavan_sudo);
}

extern int do_cavan_super_upgrade(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doSuperUpgrade(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "super_upgrade", do_cavan_super_upgrade);
}

extern int do_cavan_swan_check(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doSwanCheck(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "swan_check", do_cavan_swan_check);
}

extern int do_cavan_swan_emmc(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doSwanEmmc(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "swan_emmc", do_cavan_swan_emmc);
}

extern int do_cavan_swan_fac(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doSwanFac(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "swan_fac", do_cavan_swan_fac);
}

extern int do_cavan_swan_ipu(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doSwanIpu(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "swan_ipu", do_cavan_swan_ipu);
}

extern int do_cavan_swan_mac(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doSwanMac(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "swan_mac", do_cavan_swan_mac);
}

extern int do_cavan_swan_md5(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doSwanMd5(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "swan_md5", do_cavan_swan_md5);
}

extern int do_cavan_swan_mkfs(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doSwanMkfs(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "swan_mkfs", do_cavan_swan_mkfs);
}

extern int do_cavan_swan_sfdisk(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doSwanSfdisk(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "swan_sfdisk", do_cavan_swan_sfdisk);
}

extern int do_cavan_swan_ts(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doSwanTs(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "swan_ts", do_cavan_swan_ts);
}

extern int do_cavan_swan_upgrade(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doSwanUpgrade(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "swan_upgrade", do_cavan_swan_upgrade);
}

extern int do_cavan_swan_vk(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doSwanVk(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "swan_vk", do_cavan_swan_vk);
}

extern int do_cavan_swan_vn(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doSwanVn(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "swan_vn", do_cavan_swan_vn);
}

extern int do_cavan_system_init(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doSystemInit(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "system_init", do_cavan_system_init);
}

extern int do_cavan_tcp_copy(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doTcpCopy(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "tcp_copy", do_cavan_tcp_copy);
}

extern int do_cavan_tcp_dd(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doTcpDd(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "tcp_dd", do_cavan_tcp_dd);
}

extern int do_cavan_tcp_dd_server(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doTcpDdServer(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "tcp_dd_server", do_cavan_tcp_dd_server);
}

extern int do_cavan_tcp_exec(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doTcpExec(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "tcp_exec", do_cavan_tcp_exec);
}

extern int do_cavan_tcp_keypad(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doTcpKeypad(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "tcp_keypad", do_cavan_tcp_keypad);
}

extern int do_cavan_tcp_proxy(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doTcpProxy(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "tcp_proxy", do_cavan_tcp_proxy);
}

extern int do_cavan_tee(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doTee(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "tee", do_cavan_tee);
}

extern int do_cavan_textlen(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doTextlen(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "textlen", do_cavan_textlen);
}

extern int do_cavan_tftp_auto_dd(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doTftpAutoDd(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "tftp_auto_dd", do_cavan_tftp_auto_dd);
}

extern int do_cavan_tftp_command(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doTftpCommand(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "tftp_command", do_cavan_tftp_command);
}

extern int do_cavan_tftp_copy(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doTftpCopy(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "tftp_copy", do_cavan_tftp_copy);
}

extern int do_cavan_tftp_dd(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doTftpDd(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "tftp_dd", do_cavan_tftp_dd);
}

extern int do_cavan_tftp_dd_server(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doTftpDdServer(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "tftp_dd_server", do_cavan_tftp_dd_server);
}

extern int do_cavan_touch(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doTouch(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "touch", do_cavan_touch);
}

extern int do_cavan_tty_mode(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doTtyMode(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "tty_mode", do_cavan_tty_mode);
}

extern int do_cavan_umount(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doUmount(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "umount", do_cavan_umount);
}

extern int do_cavan_usb(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doUsb(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "usb", do_cavan_usb);
}

extern int do_cavan_usb_copy(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doUsbCopy(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "usb_copy", do_cavan_usb_copy);
}

extern int do_cavan_usb_dd(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doUsbDd(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "usb_dd", do_cavan_usb_dd);
}

extern int do_cavan_usb_dd_server(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doUsbDdServer(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "usb_dd_server", do_cavan_usb_dd_server);
}

extern int do_cavan_vfat(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doVfat(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "vfat", do_cavan_vfat);
}

extern int do_cavan_web_proxy(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doWebProxy(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "web_proxy", do_cavan_web_proxy);
}

extern int do_cavan_mkfs(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doMkfs(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "mkfs", do_cavan_mkfs);
}

extern int do_cavan_calculator_cpp(int argc, char *argv[]);

JNIEXPORT jint Java_com_cavan_cavanutils_CavanNative_doCalculatorCpp(JNIEnv *env, jclass clazz, jobjectArray args)
{
	return CavanMainExecute(env, args, "calculator_cpp", do_cavan_calculator_cpp);
}
