/* This file was automatically generated by Fuang.Cao, Do not modify */

#include "CavanMain.h"

JNIEXPORT jboolean Java_com_cavan_cavanutils_CavanUtils_kill(JNIEnv *env, jclass clazz, jstring nameStr)
{
	const char *name;
	jboolean success;

	name = (char *) (*env)->GetStringUTFChars(env, nameStr, NULL);
	if (name == NULL) {
		return false;
	}

	success = CavanProcessKill(name);
	(*env)->ReleaseStringUTFChars(env, nameStr, name);

	return success;
}
