LOCAL_PATH := $(call my-dir)

ifneq ($(TARGET_SIMULATOR),true)

include $(CLEAR_VARS)

LOCAL_MODULE := sensors.$(if $(BOARD_PRODUCT_NAME),$(BOARD_PRODUCT_NAME),$(TARGET_BOARD_HARDWARE))

LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)/hw

LOCAL_MODULE_TAGS := eng

LOCAL_CFLAGS := -DLOG_TAG=\"Sensors\" -DCONFIG_BUILD_FOR_ANDROID -Wall -Werror

LOCAL_C_INCLUDES := \
	$(LOCAL_PATH) \

LOCAL_SRC_FILES := \
			cavan_sensor_core.c

LOCAL_SHARED_LIBRARIES := libutils liblog

LOCAL_PRELINK_MODULE := false

include $(BUILD_SHARED_LIBRARY)

endif
