EXTRA_CFLAGS += -I drivers/cavan/include/
obj-$(CONFIG_CAVAN_INPUT_CORE) += cavan_input.o
cavan_input-objs += cavan_input_core.o cavan_sensor_core.o cavan_ts_core.o cavan_i2c.o cavan_sysfs.o cavan_thread.o cavan_firmware.o cavan_io.o
