#!/bin/bash

AA="1111"
BB="2222"
${AA-${BB}} => 1111

BB="2222"
${AA-${BB}} => 2222

echo disabled > /sys/bus/usb/devices/2-1/power/wakeup
echo on > /sys/bus/usb/devices/2-1/power/control

$LINENO

[[ "$1" == -* ]] && echo OK
