#!/bin/bash

AA="1111"
BB="2222"
${AA-${BB}} => 1111

BB="2222"
${AA-${BB}} => 2222

echo disabled > /sys/bus/usb/devices/2-1/power/wakeup
echo on > /sys/bus/usb/devices/2-1/power/control

$LINENO

[[ "$1" == -* ]] && echo OK

AA=1234567890
${AA:8:1} => 9
${AA:8:2} => 90

AA="11.zip.22.zip"
${AA/.zip/-sign.zip} => 11-sign.zip.22.zip
${AA//.zip/-sign.zip} => 11-sign.zip.22-sign.zip

FILE_NAME="11/22/33/44/55/66"
${FILE_NAME##*/} => 66
${FILE_NAME#*/} => 22/33/44/55/66
${FILE_NAME%%/*} => 11
${FILE_NAME%/*} => 11/22/33/44/55

AA="123456"
${#AA} => 6 -- length of AA

ARRAY=(11 22 33 44 55)
${#ARRAY[@]} => 5 -- element count of ARRAY
${#ARRAY[0]} => 2 -- length of ARRAY[0]

for ((i = 0; i < 10; i++))
do
	echo $i
done
