LOCAL_PATH := $(call my-dir)

CAVAN_CFLAGS := -DCONFIG_BUILD_FOR_ANDROID=1 -Werror
CAVAN_C_INCLUDES := $(LOCAL_PATH)/../include
CAVAN_SRC_FILES := \
	$(patsubst $(LOCAL_PATH)/%,%,$(wildcard $(LOCAL_PATH)/*.c))

include $(CLEAR_VARS)
LOCAL_MODULE := libcavan
LOCAL_CFLAGS := $(CAVAN_CFLAGS)
LOCAL_C_INCLUDES := $(CAVAN_C_INCLUDES)
LOCAL_SRC_FILES := $(CAVAN_SRC_FILES)
LOCAL_SHARED_LIBRARIES := libutils
include $(BUILD_STATIC_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := libcavan
LOCAL_CFLAGS := $(CAVAN_CFLAGS)
LOCAL_C_INCLUDES := $(CAVAN_C_INCLUDES)
LOCAL_SRC_FILES := $(CAVAN_SRC_FILES)
LOCAL_PRELINK_MODULE := false
LOCAL_MODULE_TAGS := optional
LOCAL_SHARED_LIBRARIES := libutils
include $(BUILD_SHARED_LIBRARY)
