/* This class was automatically generated by Fuang.Cao, Do not modify */

package com.cavan.cavanjni;

import java.util.HashMap;

interface ICavanCommand {
	public int main(String... args);
}

class CavanCommandAbspath implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doAbspath(args);
	}
}

class CavanCommandAlarm implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doAlarm(args);
	}
}

class CavanCommandAlc5671Clock implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doAlc5671Clock(args);
	}
}

class CavanCommandAutoDd implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doAutoDd(args);
	}
}

class CavanCommandAutoInput implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doAutoInput(args);
	}
}

class CavanCommandAutoMount implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doAutoMount(args);
	}
}

class CavanCommandBattery implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doBattery(args);
	}
}

class CavanCommandBatteryLevel implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doBatteryLevel(args);
	}
}

class CavanCommandBdata implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doBdata(args);
	}
}

class CavanCommandBkernel implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doBkernel(args);
	}
}

class CavanCommandBmpView implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doBmpView(args);
	}
}

class CavanCommandBootimg implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doBootimg(args);
	}
}

class CavanCommandBramdisk implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doBramdisk(args);
	}
}

class CavanCommandBrecovery implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doBrecovery(args);
	}
}

class CavanCommandBsystem implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doBsystem(args);
	}
}

class CavanCommandBuboot implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doBuboot(args);
	}
}

class CavanCommandCalculator implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doCalculator(args);
	}
}

class CavanCommandChroot implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doChroot(args);
	}
}

class CavanCommandChtty implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doChtty(args);
	}
}

class CavanCommandCopy implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doCopy(args);
	}
}

class CavanCommandDd implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doDd(args);
	}
}

class CavanCommandDf implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doDf(args);
	}
}

class CavanCommandDisplay implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doDisplay(args);
	}
}

class CavanCommandDos2unix implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doDos2unix(args);
	}
}

class CavanCommandEavooSellStatistic implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doEavooSellStatistic(args);
	}
}

class CavanCommandEcc implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doEcc(args);
	}
}

class CavanCommandEventRepeater implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doEventRepeater(args);
	}
}

class CavanCommandExt2 implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doExt2(args);
	}
}

class CavanCommandFbCapture implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doFbCapture(args);
	}
}

class CavanCommandFdisk implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doFdisk(args);
	}
}

class CavanCommandFileCrc32 implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doFileCrc32(args);
	}
}

class CavanCommandFileJoin implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doFileJoin(args);
	}
}

class CavanCommandFileLoop implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doFileLoop(args);
	}
}

class CavanCommandFileSplit implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doFileSplit(args);
	}
}

class CavanCommandFtp implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doFtp(args);
	}
}

class CavanCommandFtpServer implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doFtpServer(args);
	}
}

class CavanCommandGitDaemon implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doGitDaemon(args);
	}
}

class CavanCommandHeartRate implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doHeartRate(args);
	}
}

class CavanCommandI2c implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doI2c(args);
	}
}

class CavanCommandImageDd implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doImageDd(args);
	}
}

class CavanCommandInotify implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doInotify(args);
	}
}

class CavanCommandInput implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doInput(args);
	}
}

class CavanCommandJw650Lcd implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doJw650Lcd(args);
	}
}

class CavanCommandJwpUdp implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doJwpUdp(args);
	}
}

class CavanCommandLm49350Clock implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doLm49350Clock(args);
	}
}

class CavanCommandLoopRun implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doLoopRun(args);
	}
}

class CavanCommandMd5sum implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doMd5sum(args);
	}
}

class CavanCommandMkdir implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doMkdir(args);
	}
}

class CavanCommandMknp implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doMknp(args);
	}
}

class CavanCommandMksdcard implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doMksdcard(args);
	}
}

class CavanCommandModemUpgrade implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doModemUpgrade(args);
	}
}

class CavanCommandMount implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doMount(args);
	}
}

class CavanCommandMove implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doMove(args);
	}
}

class CavanCommandMtd implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doMtd(args);
	}
}

class CavanCommandNetDiscovery implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doNetDiscovery(args);
	}
}

class CavanCommandNetMonitor implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doNetMonitor(args);
	}
}

class CavanCommandNetwork implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doNetwork(args);
	}
}

class CavanCommandP2p implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doP2p(args);
	}
}

class CavanCommandPartProbe implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doPartProbe(args);
	}
}

class CavanCommandPartShow implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doPartShow(args);
	}
}

class CavanCommandPartTable implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doPartTable(args);
	}
}

class CavanCommandPing implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doPing(args);
	}
}

class CavanCommandPollEvent implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doPollEvent(args);
	}
}

class CavanCommandPollInput implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doPollInput(args);
	}
}

class CavanCommandRamdisk implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doRamdisk(args);
	}
}

class CavanCommandRedpacket implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doRedpacket(args);
	}
}

class CavanCommandRemove implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doRemove(args);
	}
}

class CavanCommandResize implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doResize(args);
	}
}

class CavanCommandRle implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doRle(args);
	}
}

class CavanCommandScreenMirror implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doScreenMirror(args);
	}
}

class CavanCommandService implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doService(args);
	}
}

class CavanCommandServiceManager implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doServiceManager(args);
	}
}

class CavanCommandSha1sum implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doSha1sum(args);
	}
}

class CavanCommandShowFile implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doShowFile(args);
	}
}

class CavanCommandShrink implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doShrink(args);
	}
}

class CavanCommandSprdAt implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doSprdAt(args);
	}
}

class CavanCommandSprdWriteImei implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doSprdWriteImei(args);
	}
}

class CavanCommandSsh implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doSsh(args);
	}
}

class CavanCommandSshCopy implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doSshCopy(args);
	}
}

class CavanCommandSshd implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doSshd(args);
	}
}

class CavanCommandSshDd implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doSshDd(args);
	}
}

class CavanCommandSu implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doSu(args);
	}
}

class CavanCommandSudo implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doSudo(args);
	}
}

class CavanCommandSuperUpgrade implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doSuperUpgrade(args);
	}
}

class CavanCommandSwanCheck implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doSwanCheck(args);
	}
}

class CavanCommandSwanEmmc implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doSwanEmmc(args);
	}
}

class CavanCommandSwanFac implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doSwanFac(args);
	}
}

class CavanCommandSwanIpu implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doSwanIpu(args);
	}
}

class CavanCommandSwanMac implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doSwanMac(args);
	}
}

class CavanCommandSwanMd5 implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doSwanMd5(args);
	}
}

class CavanCommandSwanMkfs implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doSwanMkfs(args);
	}
}

class CavanCommandSwanSfdisk implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doSwanSfdisk(args);
	}
}

class CavanCommandSwanTs implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doSwanTs(args);
	}
}

class CavanCommandSwanUpgrade implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doSwanUpgrade(args);
	}
}

class CavanCommandSwanVk implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doSwanVk(args);
	}
}

class CavanCommandSwanVn implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doSwanVn(args);
	}
}

class CavanCommandSystemInit implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doSystemInit(args);
	}
}

class CavanCommandTcpBridge implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doTcpBridge(args);
	}
}

class CavanCommandTcpCopy implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doTcpCopy(args);
	}
}

class CavanCommandTcpDd implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doTcpDd(args);
	}
}

class CavanCommandTcpDdServer implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doTcpDdServer(args);
	}
}

class CavanCommandTcpExec implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doTcpExec(args);
	}
}

class CavanCommandTcpInstall implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doTcpInstall(args);
	}
}

class CavanCommandTcpKeypad implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doTcpKeypad(args);
	}
}

class CavanCommandTcpProxy implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doTcpProxy(args);
	}
}

class CavanCommandTcpRepeater implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doTcpRepeater(args);
	}
}

class CavanCommandTee implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doTee(args);
	}
}

class CavanCommandTextlen implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doTextlen(args);
	}
}

class CavanCommandTftpAutoDd implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doTftpAutoDd(args);
	}
}

class CavanCommandTftpCommand implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doTftpCommand(args);
	}
}

class CavanCommandTftpCopy implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doTftpCopy(args);
	}
}

class CavanCommandTftpDd implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doTftpDd(args);
	}
}

class CavanCommandTftpDdServer implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doTftpDdServer(args);
	}
}

class CavanCommandTouch implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doTouch(args);
	}
}

class CavanCommandTtyMode implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doTtyMode(args);
	}
}

class CavanCommandUmount implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doUmount(args);
	}
}

class CavanCommandUsb implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doUsb(args);
	}
}

class CavanCommandUsbCopy implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doUsbCopy(args);
	}
}

class CavanCommandUsbDd implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doUsbDd(args);
	}
}

class CavanCommandUsbDdServer implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doUsbDdServer(args);
	}
}

class CavanCommandVfat implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doVfat(args);
	}
}

class CavanCommandWebProxy implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doWebProxy(args);
	}
}

class CavanCommandMkfs implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doMkfs(args);
	}
}

class CavanCommandCppCalculator implements ICavanCommand {
	@Override
	public int main(String... args) {
		return CavanNative.doCppCalculator(args);
	}
}

public class CavanNative {

	public static HashMap<String, ICavanCommand> sHashMap = new HashMap<String, ICavanCommand>();

	static {
		System.loadLibrary("cavan-jni");

		sHashMap.put("abspath", new CavanCommandAbspath());
		sHashMap.put("alarm", new CavanCommandAlarm());
		sHashMap.put("alc5671_clock", new CavanCommandAlc5671Clock());
		sHashMap.put("auto_dd", new CavanCommandAutoDd());
		sHashMap.put("auto_input", new CavanCommandAutoInput());
		sHashMap.put("auto_mount", new CavanCommandAutoMount());
		sHashMap.put("battery", new CavanCommandBattery());
		sHashMap.put("battery_level", new CavanCommandBatteryLevel());
		sHashMap.put("bdata", new CavanCommandBdata());
		sHashMap.put("bkernel", new CavanCommandBkernel());
		sHashMap.put("bmp_view", new CavanCommandBmpView());
		sHashMap.put("bootimg", new CavanCommandBootimg());
		sHashMap.put("bramdisk", new CavanCommandBramdisk());
		sHashMap.put("brecovery", new CavanCommandBrecovery());
		sHashMap.put("bsystem", new CavanCommandBsystem());
		sHashMap.put("buboot", new CavanCommandBuboot());
		sHashMap.put("calculator", new CavanCommandCalculator());
		sHashMap.put("chroot", new CavanCommandChroot());
		sHashMap.put("chtty", new CavanCommandChtty());
		sHashMap.put("copy", new CavanCommandCopy());
		sHashMap.put("dd", new CavanCommandDd());
		sHashMap.put("df", new CavanCommandDf());
		sHashMap.put("display", new CavanCommandDisplay());
		sHashMap.put("dos2unix", new CavanCommandDos2unix());
		sHashMap.put("eavoo_sell_statistic", new CavanCommandEavooSellStatistic());
		sHashMap.put("ecc", new CavanCommandEcc());
		sHashMap.put("event_repeater", new CavanCommandEventRepeater());
		sHashMap.put("ext2", new CavanCommandExt2());
		sHashMap.put("fb_capture", new CavanCommandFbCapture());
		sHashMap.put("fdisk", new CavanCommandFdisk());
		sHashMap.put("file_crc32", new CavanCommandFileCrc32());
		sHashMap.put("file_join", new CavanCommandFileJoin());
		sHashMap.put("file_loop", new CavanCommandFileLoop());
		sHashMap.put("file_split", new CavanCommandFileSplit());
		sHashMap.put("ftp", new CavanCommandFtp());
		sHashMap.put("ftp_server", new CavanCommandFtpServer());
		sHashMap.put("git_daemon", new CavanCommandGitDaemon());
		sHashMap.put("heart_rate", new CavanCommandHeartRate());
		sHashMap.put("i2c", new CavanCommandI2c());
		sHashMap.put("image_dd", new CavanCommandImageDd());
		sHashMap.put("inotify", new CavanCommandInotify());
		sHashMap.put("input", new CavanCommandInput());
		sHashMap.put("jw650_lcd", new CavanCommandJw650Lcd());
		sHashMap.put("jwp_udp", new CavanCommandJwpUdp());
		sHashMap.put("lm49350_clock", new CavanCommandLm49350Clock());
		sHashMap.put("loop_run", new CavanCommandLoopRun());
		sHashMap.put("md5sum", new CavanCommandMd5sum());
		sHashMap.put("mkdir", new CavanCommandMkdir());
		sHashMap.put("mknp", new CavanCommandMknp());
		sHashMap.put("mksdcard", new CavanCommandMksdcard());
		sHashMap.put("modem_upgrade", new CavanCommandModemUpgrade());
		sHashMap.put("mount", new CavanCommandMount());
		sHashMap.put("move", new CavanCommandMove());
		sHashMap.put("mtd", new CavanCommandMtd());
		sHashMap.put("net_discovery", new CavanCommandNetDiscovery());
		sHashMap.put("net_monitor", new CavanCommandNetMonitor());
		sHashMap.put("network", new CavanCommandNetwork());
		sHashMap.put("p2p", new CavanCommandP2p());
		sHashMap.put("part_probe", new CavanCommandPartProbe());
		sHashMap.put("part_show", new CavanCommandPartShow());
		sHashMap.put("part_table", new CavanCommandPartTable());
		sHashMap.put("ping", new CavanCommandPing());
		sHashMap.put("poll_event", new CavanCommandPollEvent());
		sHashMap.put("poll_input", new CavanCommandPollInput());
		sHashMap.put("ramdisk", new CavanCommandRamdisk());
		sHashMap.put("redpacket", new CavanCommandRedpacket());
		sHashMap.put("remove", new CavanCommandRemove());
		sHashMap.put("resize", new CavanCommandResize());
		sHashMap.put("rle", new CavanCommandRle());
		sHashMap.put("screen_mirror", new CavanCommandScreenMirror());
		sHashMap.put("service", new CavanCommandService());
		sHashMap.put("service_manager", new CavanCommandServiceManager());
		sHashMap.put("sha1sum", new CavanCommandSha1sum());
		sHashMap.put("show_file", new CavanCommandShowFile());
		sHashMap.put("shrink", new CavanCommandShrink());
		sHashMap.put("sprd_at", new CavanCommandSprdAt());
		sHashMap.put("sprd_write_imei", new CavanCommandSprdWriteImei());
		sHashMap.put("ssh", new CavanCommandSsh());
		sHashMap.put("ssh_copy", new CavanCommandSshCopy());
		sHashMap.put("sshd", new CavanCommandSshd());
		sHashMap.put("ssh_dd", new CavanCommandSshDd());
		sHashMap.put("su", new CavanCommandSu());
		sHashMap.put("sudo", new CavanCommandSudo());
		sHashMap.put("super_upgrade", new CavanCommandSuperUpgrade());
		sHashMap.put("swan_check", new CavanCommandSwanCheck());
		sHashMap.put("swan_emmc", new CavanCommandSwanEmmc());
		sHashMap.put("swan_fac", new CavanCommandSwanFac());
		sHashMap.put("swan_ipu", new CavanCommandSwanIpu());
		sHashMap.put("swan_mac", new CavanCommandSwanMac());
		sHashMap.put("swan_md5", new CavanCommandSwanMd5());
		sHashMap.put("swan_mkfs", new CavanCommandSwanMkfs());
		sHashMap.put("swan_sfdisk", new CavanCommandSwanSfdisk());
		sHashMap.put("swan_ts", new CavanCommandSwanTs());
		sHashMap.put("swan_upgrade", new CavanCommandSwanUpgrade());
		sHashMap.put("swan_vk", new CavanCommandSwanVk());
		sHashMap.put("swan_vn", new CavanCommandSwanVn());
		sHashMap.put("system_init", new CavanCommandSystemInit());
		sHashMap.put("tcp_bridge", new CavanCommandTcpBridge());
		sHashMap.put("tcp_copy", new CavanCommandTcpCopy());
		sHashMap.put("tcp_dd", new CavanCommandTcpDd());
		sHashMap.put("tcp_dd_server", new CavanCommandTcpDdServer());
		sHashMap.put("tcp_exec", new CavanCommandTcpExec());
		sHashMap.put("tcp_install", new CavanCommandTcpInstall());
		sHashMap.put("tcp_keypad", new CavanCommandTcpKeypad());
		sHashMap.put("tcp_proxy", new CavanCommandTcpProxy());
		sHashMap.put("tcp_repeater", new CavanCommandTcpRepeater());
		sHashMap.put("tee", new CavanCommandTee());
		sHashMap.put("textlen", new CavanCommandTextlen());
		sHashMap.put("tftp_auto_dd", new CavanCommandTftpAutoDd());
		sHashMap.put("tftp_command", new CavanCommandTftpCommand());
		sHashMap.put("tftp_copy", new CavanCommandTftpCopy());
		sHashMap.put("tftp_dd", new CavanCommandTftpDd());
		sHashMap.put("tftp_dd_server", new CavanCommandTftpDdServer());
		sHashMap.put("touch", new CavanCommandTouch());
		sHashMap.put("tty_mode", new CavanCommandTtyMode());
		sHashMap.put("umount", new CavanCommandUmount());
		sHashMap.put("usb", new CavanCommandUsb());
		sHashMap.put("usb_copy", new CavanCommandUsbCopy());
		sHashMap.put("usb_dd", new CavanCommandUsbDd());
		sHashMap.put("usb_dd_server", new CavanCommandUsbDdServer());
		sHashMap.put("vfat", new CavanCommandVfat());
		sHashMap.put("web_proxy", new CavanCommandWebProxy());
		sHashMap.put("mkfs", new CavanCommandMkfs());
		sHashMap.put("cpp_calculator", new CavanCommandCppCalculator());
	}

	public static native int doAbspath(String... args);
	public static native int doAlarm(String... args);
	public static native int doAlc5671Clock(String... args);
	public static native int doAutoDd(String... args);
	public static native int doAutoInput(String... args);
	public static native int doAutoMount(String... args);
	public static native int doBattery(String... args);
	public static native int doBatteryLevel(String... args);
	public static native int doBdata(String... args);
	public static native int doBkernel(String... args);
	public static native int doBmpView(String... args);
	public static native int doBootimg(String... args);
	public static native int doBramdisk(String... args);
	public static native int doBrecovery(String... args);
	public static native int doBsystem(String... args);
	public static native int doBuboot(String... args);
	public static native int doCalculator(String... args);
	public static native int doChroot(String... args);
	public static native int doChtty(String... args);
	public static native int doCopy(String... args);
	public static native int doDd(String... args);
	public static native int doDf(String... args);
	public static native int doDisplay(String... args);
	public static native int doDos2unix(String... args);
	public static native int doEavooSellStatistic(String... args);
	public static native int doEcc(String... args);
	public static native int doEventRepeater(String... args);
	public static native int doExt2(String... args);
	public static native int doFbCapture(String... args);
	public static native int doFdisk(String... args);
	public static native int doFileCrc32(String... args);
	public static native int doFileJoin(String... args);
	public static native int doFileLoop(String... args);
	public static native int doFileSplit(String... args);
	public static native int doFtp(String... args);
	public static native int doFtpServer(String... args);
	public static native int doGitDaemon(String... args);
	public static native int doHeartRate(String... args);
	public static native int doI2c(String... args);
	public static native int doImageDd(String... args);
	public static native int doInotify(String... args);
	public static native int doInput(String... args);
	public static native int doJw650Lcd(String... args);
	public static native int doJwpUdp(String... args);
	public static native int doLm49350Clock(String... args);
	public static native int doLoopRun(String... args);
	public static native int doMd5sum(String... args);
	public static native int doMkdir(String... args);
	public static native int doMknp(String... args);
	public static native int doMksdcard(String... args);
	public static native int doModemUpgrade(String... args);
	public static native int doMount(String... args);
	public static native int doMove(String... args);
	public static native int doMtd(String... args);
	public static native int doNetDiscovery(String... args);
	public static native int doNetMonitor(String... args);
	public static native int doNetwork(String... args);
	public static native int doP2p(String... args);
	public static native int doPartProbe(String... args);
	public static native int doPartShow(String... args);
	public static native int doPartTable(String... args);
	public static native int doPing(String... args);
	public static native int doPollEvent(String... args);
	public static native int doPollInput(String... args);
	public static native int doRamdisk(String... args);
	public static native int doRedpacket(String... args);
	public static native int doRemove(String... args);
	public static native int doResize(String... args);
	public static native int doRle(String... args);
	public static native int doScreenMirror(String... args);
	public static native int doService(String... args);
	public static native int doServiceManager(String... args);
	public static native int doSha1sum(String... args);
	public static native int doShowFile(String... args);
	public static native int doShrink(String... args);
	public static native int doSprdAt(String... args);
	public static native int doSprdWriteImei(String... args);
	public static native int doSsh(String... args);
	public static native int doSshCopy(String... args);
	public static native int doSshd(String... args);
	public static native int doSshDd(String... args);
	public static native int doSu(String... args);
	public static native int doSudo(String... args);
	public static native int doSuperUpgrade(String... args);
	public static native int doSwanCheck(String... args);
	public static native int doSwanEmmc(String... args);
	public static native int doSwanFac(String... args);
	public static native int doSwanIpu(String... args);
	public static native int doSwanMac(String... args);
	public static native int doSwanMd5(String... args);
	public static native int doSwanMkfs(String... args);
	public static native int doSwanSfdisk(String... args);
	public static native int doSwanTs(String... args);
	public static native int doSwanUpgrade(String... args);
	public static native int doSwanVk(String... args);
	public static native int doSwanVn(String... args);
	public static native int doSystemInit(String... args);
	public static native int doTcpBridge(String... args);
	public static native int doTcpCopy(String... args);
	public static native int doTcpDd(String... args);
	public static native int doTcpDdServer(String... args);
	public static native int doTcpExec(String... args);
	public static native int doTcpInstall(String... args);
	public static native int doTcpKeypad(String... args);
	public static native int doTcpProxy(String... args);
	public static native int doTcpRepeater(String... args);
	public static native int doTee(String... args);
	public static native int doTextlen(String... args);
	public static native int doTftpAutoDd(String... args);
	public static native int doTftpCommand(String... args);
	public static native int doTftpCopy(String... args);
	public static native int doTftpDd(String... args);
	public static native int doTftpDdServer(String... args);
	public static native int doTouch(String... args);
	public static native int doTtyMode(String... args);
	public static native int doUmount(String... args);
	public static native int doUsb(String... args);
	public static native int doUsbCopy(String... args);
	public static native int doUsbDd(String... args);
	public static native int doUsbDdServer(String... args);
	public static native int doVfat(String... args);
	public static native int doWebProxy(String... args);
	public static native int doMkfs(String... args);
	public static native int doCppCalculator(String... args);
}
