#!/bin/bash

for cmd in branch  interactive ui diff grep status

do
	echo "git config color.${cmd} auto"
	git config --global color.${cmd} auto;
done

#for cmd in diff.frag grep.match status.changed diff.commit grep.external status.added interactive.prompt status.updated branch.remote diff.whitespace diff.meta diff.new status.header branch.current interactive.header status.nobranch branch.local diff.old interactive.help status.untracked branch.plain diff.plain
#do
#	echo "git config color.${cmd} normal"
#	git config color.${cmd} normal;
#done
#
#for cmd in pager
#do
#	git config color.${cmd} true
#done
