#!/usr/bin/env perl

use warnings;
use strict;
use 5.010;

my $file_cfg = $ARGV[0];
my $file_xml = $ARGV[1];

say "file_cfg = $file_cfg, file_xml = $file_xml";

open(FILE_CFG, "<", $file_cfg) or die "Failed to open file $file_cfg: $!";
open(FILE_XML, "<", $file_xml) or die "Failed to open file $file_xml: $!";

my @cfg_lines = <FILE_CFG>;
my @xml_lines = <FILE_XML>;

sub find_new_value()
{
	my @values;
	my $addr = $_[0];

	foreach (@xml_lines) {
		if (/^setmem\s*\/32\s+0x$addr\s*=\s*0x(\w+)/i) {
			push @values, $1;
		}
	}

	@values;
}

foreach my $line (@cfg_lines) {
	if ($line =~ /^DATA\s+4\s*,\s*0x(02(?:0e|1b)\w+)\s*,\s*0x(\w+)/i) {
		my $addr = "\L$1";
		my $value_old = "\U$2";
		my @values = &find_new_value($addr);
		next if (@values < 1);
		my $value_new = "\U$values[0]";
		next if ($value_old eq $value_new);
		say "addr = 0x$addr, value: 0x$value_old => 0x$value_new";
		$line = "DATA 4,\t0x$addr, 0x$value_new\n";
	}
}

open(FILE_CFG, ">", $file_cfg) or die "Failed to open file $file_cfg: $!";
print FILE_CFG @cfg_lines;
