#!/usr/bin/env python

import sys, os
from sys import argv

def pr_red_info(message):
	print "\033[31m%s\033[0m" % message

def pr_green_info(message):
	print "\033[32m%s\033[0m" % message

if len(argv) < 3:
	pr_red_info("Too a few argument")
	sys.exit(-1)

target_path = argv[-1]

for fn in argv[1:-1]:
	print "adb push %s => %s" % (fn, target_path)
	if os.system("adb push %s %s" % (fn, target_path)) != 0:
		pr_red_info("failed")
		sys.exit(-1)

pr_green_info("OK")
