#!/bin/bash

PORT=${1-"8888"}
BASE_PATH=${2-${HOME}/git}

mkdir ${BASE_PATH} -p || exit 1

echo "BASE_PATH = ${BASE_PATH}"
echo "PORT = ${PORT}"

`git --exec-path`/git-daemon --verbose --port=${PORT} --export-all --enable=receive-pack --enable=upload-pack --enable=upload-archive --base-path=${BASE_PATH}
