#!/usr/bin/env python

import sys
from python import cavan_adb
from python import cavan_stdio

if __name__ == "__main__":
	if len(sys.argv) < 1:
		sys.exit(0)

	manager = cavan_adb.AdbManager()
	if manager.doInstall(sys.argv[1:]):
		cavan_stdio.pr_green_info("OK")
		sys.exit(0)

	cavan_stdio.pr_red_info("Failed")
	sys.exit(-1)
