#!/usr/bin/env python

import sys, os

from python import cavan_tc3587xx
from python.cavan_stdio import pr_red_info, pr_green_info

if __name__ == "__main__":
	if len(sys.argv) > 2:
		convert = cavan_tc3587xx.TC3587XX_Converter()
		if not convert.doConvertXml(sys.argv[1]):
			sys.exit(-1)

		if not convert.save(sys.argv[2]):
			sys.exit(-1)

	pr_green_info("OK")
