#!/bin/bash

function cavan_visual_command()
{
	echo $*

	$* || return 1

	return 0
}

while read line
do
	set $line

	cavan_visual_command cd $1 || continue
	cavan_visual_command cavan-git-svn-repo sync || continue
	cavan_visual_command cavan-git-svn-repo backup

	while :
	do
		shift
		[ "$1" ] || break
		cavan_visual_command ./mk -o=2sim $1 n
	done
done < $1
