#!/bin/bash

BASE_PATH=${1-${HOME}/git}
PORT=${2-"8888"}

mkdir ${BASE_PATH} -p || exit 1

echo "BASE_PATH = ${BASE_PATH}"
echo "PORT = ${PORT}"

`git --exec-path`/git-daemon --verbose --port=${PORT} --export-all --enable=receive-pack --enable=upload-pack --enable=upload-archive --base-path=${BASE_PATH}
