#!/bin/sh

"""exec" python -E $0 $@
#"""

import sys, os

from python import cavan_repo
from python.cavan_stdio import pr_red_info, pr_green_info

if __name__ == "__main__":
	if len(sys.argv) > 1:
		manager = cavan_repo.CavanGitSvnRepoManager()
		if manager.main(sys.argv):
			pr_green_info("OK")
		else:
			pr_red_info("Failed")
