#!/usr/bin/env perl

use warnings;
use strict;

use File::Spec::Functions;

sub find_soruce_files
{
	my @filelist;

	foreach my $dirname (@_) {
		if (-d $dirname) {
			opendir(my $fd, $dirname) or die "Failed to opendir $dirname: $!";

			while (readdir $fd) {
				next if /^\./;

				my $pathname = catfile($dirname, $_);
				push @filelist, &find_soruce_files($pathname);
			}

			closedir $fd;
		} elsif ($dirname =~ /\.(c|h|cpp)$/) {
			push @filelist, $dirname;
		}
	}

	@filelist;
}

my $command = shift @ARGV;
my $single_line = 1;
if ($command eq 'm') {
	$single_line = 0;
} elsif ($command ne 's') {
	die "usage: <s|m> [PATH]\n";
}

my @dirlist = @ARGV;

if (@dirlist <= 0) {
	push @dirlist, ".";
}

foreach my $pathname (&find_soruce_files(@dirlist)) {
	print "pathname = $pathname\n";

	open(FILE, "<", $pathname) or die "Failed to open file $pathname: $!";
	$_ = join '', <FILE>;

	s/[\t ]+$//mg;

	if ($single_line) {
		s/^([\t ]+.*\))[\t ]*\n[\t ]+\{/$1 \{/mg;
		s/^([\t ]+\})[\t ]*\n?[\t ]+(\w+)[\t ]*\n?[\t ]+\{/$1 $2 \{/mg;
		s/^([\t ]+\})[\t ]*\n[\t ]+(else[\t ]+if)/$1 $2/mg;
		s/^([\t ]+case.*:)[\t ]*\n[\t ]+{/$1 \{/mg;

		s/(.*=)[\t ]*\n[\t ]*\{/$1 \{/mg;
		s/^([\t ]+\})[\t ]*,[\t ]*\n[\t ]+\{/$1, \{/mg;

		s/^([\t ]*(?:struct|class)[\t ]+\w+)[\t ]*\n\{/$1 \{/mg;
	} else {
		s/^([\t ]*)\}[\t ]*(\S.*\S)[\t ]*\{[\t ]*$/$1\}\n$1$2\n$1\{/mg;
		s/^([\t ]*)(\S.*\S)[\t ]*\{[\t ]*$/$1$2\n$1\{/mg;
		s/^([\t ]*)(.*=)[\t ]*\{[^\}\n]*$/$1$2\n$1\{/mg;
		s/^([\t ]*)}[\t ]*,[\t ]*{/$1\},\n$1\{/mg;
		s/^([\t ]*)(.+:)[\t ]*\{/$1$2\n$1\t\{/mg;
	}

	s/^([\t ]+.*\))[\t ]*\\[\t ]*\n[\t ]+\{/$1 \{/mg;
	s/^([\t ]+do)[\t\\ ]*\n[\t ]+{/$1 \{/mg;
	s/=[\t ]*\{(\S.*\S)\}/= \{ $1 \}/mg;
	s/^[\t ]*(typedef[\w\t ]+)\b[\t ]*\n[\t ]*\{/$1 \{/mg;

	for my $i (1..10) {
		s/(\([^\*\(\)]+\*?[\t ]*\))([\w\(\&])/$1 $2/mg or last;
	}

	s/^[\t ]*#if(def\s*__cplusplus|[\t ]+defined[\t ]*\([\t ]*__cplusplus[\t ]*\))\s*extern\s*\"[Cc]\"\s*{\s*#endif/__BEGIN_DECLS/mg;
	s/^[\t ]*#if(def\s*__cplusplus|[\t ]+defined[\t ]*\([\t ]*__cplusplus[\t ]*\))\s*\}\s*#endif/__END_DECLS/mg;
	s/extern[\t ]+\"[Cc]\"[\t ]*\n[\t ]*{/extern "C" \{/mg;

	open(FILE, ">", "$pathname") or die "Failed to open file $pathname: $!";
	print FILE $_;
}
