EXTRA_CFLAGS += -Idrivers/cavan/include/
obj-$(CONFIG_CAVAN_MISC_SWAN_VK) += swan_vk.o
obj-$(CONFIG_CAVAN_MISC_SWAN_VN) += swan_vn.o
obj-$(CONFIG_CAVAN_MISC_TCP_KEYPAD) += tcp_keypad.o
obj-$(CONFIG_CAVAN_LEDS_PCA9685) += leds-pca9685.o
