// This File Is Automatically Generated By FuangCao
// Fuang.Cao <cavan.cfa@gmail.com>
// Create date: 2011-09-24 03:01:54

#include <cavan.h>
#include <cavan/command.h>

#ifndef CONFIG_CAVAN_MAIN_NAME
#define CONFIG_CAVAN_MAIN_NAME	"cavan-main"
#endif

#ifndef CONFIG_CAVAN_MAP_H
#define CONFIG_CAVAN_MAP_H		"cavan_map.h"
#endif

#ifndef CONFIG_CAVAN_MAP_C
#define CONFIG_CAVAN_MAP_C		"cavan_map.c"
#endif

#include CONFIG_CAVAN_MAP_H

static int cavan_main(int argc, char *argv[]);

#ifdef CONFIG_ANDROID
static const char *cavan_get_bootanimation_path(void)
{
	int i;
	const char *pathnames[] = {
		"/data/test.mp3", "/system/media/bootanimation.mp4"
	};

	for (i = 0; i < NELEM(pathnames); i++) {
		if (file_access_e(pathnames[i])) {
			return pathnames[i];
		}
	}

	return NULL;
}

static int do_cavan_bootanimation(int argc, char *argv[])
{

	if (argc > 1) {
		return do_cavan_mplayer(argc, argv);
	} else {
		const char *pathname = cavan_get_bootanimation_path();

		if (pathname) {
			char *argv_new[] = { __UNCONST("bootanimation"), __UNCONST(pathname) };

			return do_cavan_mplayer(NELEM(argv_new), argv_new);
		}
	}

	return 0;
}

static int do_cavan_remount(int argc, char *argv[])
{
	char *argv_new[] = { argv[0], "-l", "remount" };

	return do_cavan_tcp_exec(NELEM(argv_new), argv_new);
}
#endif

const struct cavan_command_map cmd_map_table[] = {
	{ CONFIG_CAVAN_MAIN_NAME, cavan_main },
	{ "calc", do_cavan_calculator },
#ifdef CONFIG_ANDROID
	{ "bootanim", do_cavan_bootanimation },
	{ "bootanimation", do_cavan_bootanimation },
	{ "remount", do_cavan_remount },
#endif

	#include CONFIG_CAVAN_MAP_C
};

int main(int argc, char *argv[])
{
	return find_and_exec_command(cmd_map_table, NELEM(cmd_map_table), argc, argv);
}

static int cavan_main(int argc, char *argv[])
{
	if (argc > 1) {
		return main(argc - 1, argv + 1);
	}

	println("%s %s", argv[0], cavan_get_build_time_string());
	println("Usage: %s [[subcommand] [arguments] ...]\n", argv[0]);
	println("https://github.com/FuangCao/cavan.git\n");
	print_command_table(cmd_map_table + 1, cmd_map_table + ARRAY_SIZE(cmd_map_table) - 1);

	return -EINVAL;
}
