// This File Is Automatically Generated By FuangCao
// Fuang.Cao <cavan.cfa@gmail.com>
// Create date: 2011-09-24 03:01:54

#include <cavan.h>
#include <cavan/command.h>
#include <cavan/permission.h>

#ifndef CONFIG_CAVAN_MAIN_NAME
#define CONFIG_CAVAN_MAIN_NAME	"cavan-main"
#endif

#ifndef CONFIG_CAVAN_MAP_H
#define CONFIG_CAVAN_MAP_H		"cavan_map.h"
#endif

#ifndef CONFIG_CAVAN_MAP_C
#define CONFIG_CAVAN_MAP_C		"cavan_map.c"
#endif

#include CONFIG_CAVAN_MAP_H

static int cavan_main(int argc, char *argv[]);

#ifdef CONFIG_ANDROID
static const char *cavan_get_bootanimation_path(void)
{
	int i;
	const char *pathnames[] = {
		"/data/test.mp3", "/system/media/bootanimation.mp4"
	};

	for (i = 0; i < NELEM(pathnames); i++) {
		if (file_access_e(pathnames[i])) {
			return pathnames[i];
		}
	}

	return NULL;
}

static int do_cavan_bootanimation(int argc, char *argv[])
{

	if (argc > 1) {
		return do_cavan_mplayer(argc, argv);
	} else {
		const char *pathname = cavan_get_bootanimation_path();

		if (pathname) {
			char *argv_new[] = { __UNCONST("bootanimation"), __UNCONST(pathname), NULL };

			return do_cavan_mplayer(2, argv_new);
		}
	}

	return 0;
}
#endif

#ifdef CONFIG_ANDROID
static int do_cavan_remount(int argc, char *argv[])
{
	return cavan_exec_command("remount", argc, argv);
}
#endif

static int do_cavan_halt(int argc, char *argv[])
{
	return cavan_exec_command("halt-force", argc, argv);
}

static int do_cavan_reboot(int argc, char *argv[])
{
	return cavan_exec_command("reboot-force", argc, argv);
}

static int do_cavan_getuid(int argc, char *argv[])
{
	uid_t uid;

	if (argc > 1) {
		uid = cavan_user_name_to_uid(argv[1]);
		if (uid == CAVAN_UID_INVALID) {
			pr_red_info("invalid user: %s", argv[1]);
			return -EINVAL;
		}
	} else {
		uid = getuid();
	}

	println("%d", uid);

	return 0;
}

static int do_cavan_getgid(int argc, char *argv[])
{
	gid_t gid;

	if (argc > 1) {
		gid = cavan_group_name_to_gid(argv[1]);
		if (gid == CAVAN_UID_INVALID) {
			pr_red_info("invalid group: %s", argv[1]);
			return -EINVAL;
		}
	} else {
		gid = getuid();
	}

	println("%d", gid);

	return 0;
}

static int do_cavan_getuser(int argc, char *argv[])
{
	uid_t uid;
	char buff[64];

	if (argc > 1) {
		uid = text2value_unsigned(argv[1], NULL, 10);
	} else {
		uid = getuid();
	}

	if (cavan_user_uid_to_name(uid, buff, sizeof(buff)) == NULL) {
		pr_red_info("unknown uid = %d", uid);
		return -EINVAL;
	}

	println("%s", buff);

	return 0;
}

static int do_cavan_getgroup(int argc, char *argv[])
{
	gid_t gid;
	char buff[64];

	if (argc > 1) {
		gid = text2value_unsigned(argv[1], NULL, 10);
	} else {
		gid = getuid();
	}

	if (cavan_user_uid_to_name(gid, buff, sizeof(buff)) == NULL) {
		pr_red_info("unknown gid = %d", gid);
		return -EINVAL;
	}

	println("%s", buff);

	return 0;
}

const struct cavan_command_map cmd_map_table[] = {
	{ CONFIG_CAVAN_MAIN_NAME, cavan_main },
	{ "calc", do_cavan_calculator },
	{ "halt", do_cavan_halt },
	{ "reboot", do_cavan_reboot },
	{ "getuid", do_cavan_getuid },
	{ "getgid", do_cavan_getgid },
	{ "getuser", do_cavan_getuser },
	{ "getgroup", do_cavan_getgroup },
#ifdef CONFIG_ANDROID
	{ "bootanim", do_cavan_bootanimation },
	{ "bootanimation", do_cavan_bootanimation },
	{ "remount", do_cavan_remount },
#endif

	#include CONFIG_CAVAN_MAP_C
};

int main(int argc, char *argv[])
{
	return find_and_exec_command(cmd_map_table, NELEM(cmd_map_table), argc, argv);
}

static int cavan_main(int argc, char *argv[])
{
	if (argc > 1) {
		return main(argc - 1, argv + 1);
	}

	println("%s %s", argv[0], cavan_get_build_time_string());
	println("Usage: %s [[subcommand] [arguments] ...]\n", argv[0]);
	println("https://github.com/FuangCao/cavan.git\n");
	print_command_table(cmd_map_table + 1, cmd_map_table + ARRAY_SIZE(cmd_map_table) - 1);

	return -EINVAL;
}
